- name: Configure Firewall Rules
  hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: Stop firewalld service
      ansible.builtin.service:
        name: firewalld
        state: stopped