- name: Helm install for master server
  hosts: master
  gather_facts: no
  tasks:

    - name: mkdir directory for harbor container images
      ansible.builtin.file:
        path: /home/harbor_images
        state: directory
        mode: '0755'

    - name: copy required files for install
      ansible.builtin.copy:
        src: /share/harbor_images
        dest: /home/