- name: Install Docker and related packages from local RPMs
  hosts: harbor
  become: yes
  tasks:

    - name: copy required files for install
      ansible.builtin.copy:
        src: /share/docker/
        dest: /home/

    - name: Install Docker and related packages
      yum:
        name:
          - /home/docker-ce-cli-24.0.6-1.el9.x86_64.rpm
          - /home/docker-ce-rootless-extras-24.0.6-1.el9.x86_64.rpm
          - /home/docker-ce-24.0.6-1.el9.x86_64.rpm
          - /home/docker-buildx-plugin-0.11.2-1.el9.x86_64.rpm
          - /home/docker-compose-plugin-2.21.0-1.el9.x86_64.rpm
          - /home/containerd.io-1.6.9-3.1.el9.x86_64.rpm
        disable_gpg_check: True
        disablerepo: baseos,appstream,extras
        state: present

    - name: Systemctl enable and start docker.service
      ansible.builtin.systemd_service:
        name: docker
        state: started
        enabled: True

    - name: Extract harbor files to desired destination
      ansible.builtin.unarchive:
        src: /share/harbor/harbor-offline-installer-v2.9.0.tgz
        dest: /home/

    - name: Copy install.sh to machine
      ansible.builtin.copy:
        src: /share/harbor/harbor.yml
        dest: /home/harbor
        mode: '0755'

    - name: Execute ./install.sh
      ansible.builtin.raw: /home/harbor/./install.sh
