- name: Harbor deployment using Helm
  hosts: all
  gather_facts: no
  become: true
  tasks:

    - name: mkdir directory for Harbor container images
      ansible.builtin.file:
        path: /home/harbor_images
        state: directory
        mode: '0755'

    - name: copy Helm chart to master
      ansible.builtin.unarchive:
        src: /share/harbor/harbor-1.13.1.tgz
        dest: /home/

    - name: Copy images to master
      ansible.builtin.unarchive:
        src: /share/harbor/harbor-images.tar
        dest: /home/
    
    - name: copy rancher/mirrored-pause to master
      ansible.builtin.copy:
        src: /share/harbor/mirrored-pause.tar
        dest: /home/

    - name: K3s load harbor-core image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/harbor-core-v2.9.1.tar

    - name: K3s load harbor-db image
      ansible.builtin.raw: k3s ctr images import /home/harbor-imagess/harbor-db-v2.9.1.tar

    - name: K3s load harbor-exporter image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/harbor-exporter-v2.9.1.tar

    - name: K3s load harbor-jobservice image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/harbor-jobservice-v2.9.1.tar

    - name: K3s load harbor-portal image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/harbor-portal-v2.9.1.tar

    - name: K3s load harbor-registryctl image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/harbor-registryctl-v2.9.1.tar

    - name: K3s load nginx-photon image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/nginx-photon-v2.9.1.tar

    - name: K3s load redis-photon image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/redis-photon-v2.9.1.tar

    - name: K3s load registry-photon image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/registry-photon-v2.9.1.tar

    - name: K3s load harbor-db image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/trivy-adapter-photon-v2.9.1.tar

    - name: K3s load rancher/mirrored-pause image
      ansible.builtin.raw: k3s ctr images import /home/mirrored-pause.tar

    - name: install Harbor using Helm
      ansible.builtin.raw: helm install harbor /home/harbor --kubeconfig /etc/rancher/k3s/k3s.yaml
    
