- name: Harbor deployment using Helm
  hosts: master
  gather_facts: no
  tasks:

    - name: mkdir directory for Harbor container images
      ansible.builtin.file:
        path: /home/harbor_images
        state: directory
        mode: '0755'

    - name: mkdir directory for Harbor Helm chart
      ansible.builtin.file:
        path: /home/harbor_deployment
        state: directory
        mode: '0755'

    - name: copy Helm chart to master
      ansible.builtin.copy:
        src: /share/harbor/harbor_deployment
        dest: /home/

    - name: Copy images to master
      ansible.builtin.unarchive:
        src: /share/harbor/harbor_images/
        dest: /home/

    - name: K3s load harbor-core image
      ansible.builtin.raw: k3s ctr images import /home/harbor_images/harbor-core-v2.9.1.tar

    - name: K3s load harbor-db image
      ansible.builtin.raw: k3s ctr images import /home/harbor_images/harbor-db-v2.9.1.tar

    - name: K3s load harbor-exporter image
      ansible.builtin.raw: k3s ctr images import /home/harbor_images/harbor-exporter-v2.9.1.tar

    - name: K3s load harbor-jobservice image
      ansible.builtin.raw: k3s ctr images import /home/harbor_images/harbor-jobservice-v2.9.1.tar

    - name: K3s load harbor-portal image
      ansible.builtin.raw: k3s ctr images import /home/harbor_images/harbor-portal-v2.9.1.tar

    - name: K3s load harbor-registryctl image
      ansible.builtin.raw: k3s ctr images import /home/harbor_images/harbor-registryctl-v2.9.1.tar

    - name: K3s load nginx-photon image
      ansible.builtin.raw: k3s ctr images import /home/harbor_images/nginx-photon-v2.9.1.tar

    - name: K3s load redis-photon image
      ansible.builtin.raw: k3s ctr images import /home/harbor_images/redis-photon-v2.9.1.tar

    - name: K3s load registry-photon image
      ansible.builtin.raw: k3s ctr images import /home/harbor_images/registry-photon-v2.9.1.tar

    - name: K3s load harbor-db image
      ansible.builtin.raw: k3s ctr images import /home/harbor_images/trivy-adapter-photon-v2.9.1.tar

    - name: install Harbor using Helm
      ansible.builtin.raw: helm install harbor /home/harbor_deployment
    
