- name: Load Harbor images using K3s ctr
  hosts: all
  gather_facts: false
  become: true
  tasks:
  
    - name: Mkdir directory for Harbor container images
      ansible.builtin.file:
        path: /home/harbor_images
        state: directory
        mode: '0755'

    - name: Copy Helm chart to all nodes
      ansible.builtin.unarchive:
        src: /share/harbor/harbor-1.13.1.tgz
        dest: /home/

    - name: Copy rancher/mirrored-pause to all nodes
      ansible.builtin.copy:
        src: /share/harbor/mirrored-pause.tar
        dest: /home/

    - name: Copy images to all nodes
      ansible.builtin.unarchive:
        src: /share/harbor/harbor-images.tar
        dest: /home/

    - name: Define Harbor images list
      set_fact:
        harbor_images:
          - harbor-core
          - harbor-db
          - harbor-exporter   
          - harbor-jobservice
          - harbor-portal
          - harbor-registryctl
          - nginx-photon
          - redis-photon
          - registry-photon
          - trivy-adapter-photon

    - name: Load Harbor images using K3s ctr
      ansible.builtin.shell:
        cmd: "k3s ctr images import /home/harbor-images/{{ item }}.tar"
      loop: "{{ harbor_images }}"

- name: Execute Helm chart
  hosts: master
  gather_facts: false
  become: true
  tasks:

    - name: Install Harbor using Helm
      ansible.builtin.shell: >-
        helm install harbor --generate-name --kubeconfig /etc/rancher/k3s/k3s.yaml
      args:
        chdir: /home/