- name: Harbor deployment using Helm
  hosts: all
  gather_facts: false
  become: true
  tasks:

    - name: mkdir directory for Harbor container images
      ansible.builtin.file:
        path: /home/harbor_images
        state: directory
        mode: '0755'

    - name: copy Helm chart to all nodes
      ansible.builtin.unarchive:
        src: /share/harbor/harbor-1.13.1.tgz
        dest: /home/

    - name: Copy images to all nodes
      ansible.builtin.unarchive:
        src: /share/harbor/harbor-images.tar
        dest: /home/
    
    - name: copy rancher/mirrored-pause to all nodes
      ansible.builtin.copy:
        src: /share/harbor/mirrored-pause.tar
        dest: /home/

    - name: K3s load harbor-core image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/harbor-core.tar

    - name: K3s load harbor-db image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/harbor-db.tar

    - name: K3s load harbor-exporter image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/harbor-exporter.tar

    - name: K3s load harbor-jobservice image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/harbor-jobservice.tar

    - name: K3s load harbor-portal image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/harbor-portal.tar

    - name: K3s load harbor-registryctl image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/harbor-registryctl.tar

    - name: K3s load nginx-photon image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/nginx-photon.tar

    - name: K3s load redis-photon image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/redis-photon.tar

    - name: K3s load registry-photon image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/registry-photon.tar

    - name: K3s load harbor-db image
      ansible.builtin.raw: k3s ctr images import /home/harbor-images/trivy-adapter-photon.tar

    - name: K3s load rancher/mirrored-pause image
      ansible.builtin.raw: k3s ctr images import /home/mirrored-pause.tar

- name: Execute Helm chart
  hosts: master
  gather_facts: false
  become: true
  tasks:

    - name: install Harbor using Helm
      ansible.builtin.raw: helm install harbor --generate name --kubeconfig /etc/rancher/k3s/k3s.yaml
    
