- name: K3s master install
  hosts: master
  gather_facts: no
  tasks:

    - name: mkdir /var/lib/rancher/k3s/agent/images/
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/agent/images/
        state: directory
        mode: '0755'

    - name: Set k3s Executable
      ansible.builtin.copy:
        src: /share/k3s/k3s
        dest: /usr/local/bin/
        mode: '0755'

    - name: Set images
      ansible.builtin.copy:
        src: /share/k3s/k3s-airgap-images-amd64.tar
        dest: /var/lib/rancher/k3s/agent/images/

    - name: Set install script
      ansible.builtin.copy:
        src: /share/k3s/install.sh
        dest: /home/
        mode: '0755'

    - name: Get file for k3s-selinux
      ansible.builtin.copy:
        src: /share/k3s/k3s-selinux-1.4-1.el9.noarch.rpm
        dest: /home/

    - name: install k3s-selinux
      ansible.builtin.yum:
        name: /home/k3s-selinux-1.4-1.el9.noarch.rpm
        disable_gpg_check: True
        disablerepo: baseos,appstream,extras,extras-common
        state: present

    - name: Execute ./install.sh
      ansible.builtin.raw: INSTALL_K3S_SKIP_DOWNLOAD=true /home/./install.sh

    - name: "Read a file content"
      shell: |
        cat /var/lib/rancher/k3s/server/node-token
      register: file_content

    - local_action: copy content="{{ file_content.stdout }}" dest="/home/rens/k3s/node-token"

    - name: Set firewall rule 6443/tcp
      firewalld:
        zone: public
        port: 6443/tcp
        permanent: true
        state: enabled

    - name: reload firewall
      ansible.builtin.raw: firewall-cmd --reload