- name: K3s master install
  hosts: master
  become: true
  gather_facts: no
  tasks:

    - name: mkdir /var/lib/rancher/k3s/agent/images/
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/agent/images/
        state: directory
        mode: '0755'

    - name: Set k3s Executable
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/k3s_files/k3s"
        dest: /usr/local/bin/
        mode: '0755'

    - name: Set images
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/k3s_files/k3s-airgap-images-amd64.tar"
        dest: /var/lib/rancher/k3s/agent/images/

    - name: Set install script
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/k3s_files/install.sh"
        dest: /home/
        mode: '0755'

    - name: Get file for k3s-selinux
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/k3s_files/k3s-selinux-1.4-1.el9.noarch.rpm"
        dest: /home/

    - name: install k3s-selinux
      ansible.builtin.yum:
        name: /home/k3s-selinux-1.4-1.el9.noarch.rpm
        disable_gpg_check: True
        disablerepo: baseos,appstream,extras,extras-common
        state: present

    - name: Execute ./install.sh
      ansible.builtin.shell: >-
        INSTALL_K3S_SKIP_DOWNLOAD=true /home/./install.sh

    - name: Get node token
      ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
      changed_when: false
      register: node_token_output

    - name: Set node_token fact.
      ansible.builtin.set_fact:
        node_token: "{{ node_token_output.stdout_lines[0] }}"

- name: Disable firewall
  hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: Stop firewalld service
      ansible.builtin.service:
        name: firewalld
        state: stopped

- name: K3s worker nodes install
  hosts: workers
  gather_facts: no
  tasks:

    - name: mkdir /var/lib/rancher/k3s/agent/images/
      ansible.builtin.file:
        path: /var/lib/rancher/k3s/agent/images/
        state: directory
        mode: '0755'

    - name: Set k3s Executable
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/k3s_files/k3s"
        dest: /usr/local/bin/
        mode: '0755'

    - name: Set images
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/k3s_files/k3s-airgap-images-amd64.tar"
        dest: /var/lib/rancher/k3s/agent/images/

    - name: Set install script
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/k3s_files/install.sh"
        dest: /home/
        mode: '0755'

    - name: Get file for k3s-selinux
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/k3s_files/k3s-selinux-1.4-1.el9.noarch.rpm"
        dest: /home/

    - name: install k3s-selinux
      ansible.builtin.yum:
        name: /home/k3s-selinux-1.4-1.el9.noarch.rpm
        disable_gpg_check: True
        disablerepo: baseos,appstream,extras,extras-common
        state: present

    - name: Install K3s on worker nodes
      ansible.builtin.shell: >-
        INSTALL_K3S_SKIP_DOWNLOAD=true \
        K3S_URL="https://{{ groups['master'][0] }}:6443" \
        K3S_TOKEN="{{ hostvars[groups['master'][0]]['node_token'] }}" \
        /home/./install.sh
      args:
        executable: /bin/bash

- name: K3s private registry configuration
  hosts: all
  gather_facts: no
  become: true
  tasks:

    - name: Create /etc/rancher/k3s/ directory on all nodes
      ansible.builtin.file:
        path: /etc/rancher/k3s/
        state: directory
        mode: '0755'

    - name: Create /etc/rancher/k3s/registries.yaml on all nodes
      copy:
        content: |
          mirrors:
            harbor.core.local:
              endpoint:
                - "http://harbor.core.local:80"
          configs:
            "harbor.core.local":
              tls:
                insecure_skip_verify: true
        dest: /etc/rancher/k3s/registries.yaml

- name: Restart K3s master node service
  hosts: master
  gather_facts: no
  become: true
  tasks:

    - name: Restart K3s service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: k3s

- name: Restart K3s-agent service on worker nodes
  hosts: workers
  gather_facts: no
  become: true
  tasks:

    - name: Restart K3s-agent service
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: k3s-agent

- name: Helm install for master server
  hosts: master
  gather_facts: no
  tasks:

    - name: copy Helm binary to desired destination
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/helm/linux-amd64/helm"
        dest: /usr/local/bin/
        mode: '0755'

    - name: export kubeconfig
      ansible.builtin.shell: >-
        export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

- name: Load Harbor images using K3s ctr
  hosts: all
  gather_facts: false
  become: true
  tasks:
  
    - name: Mkdir directory for Harbor container images
      ansible.builtin.file:
        path: /home/harbor_images
        state: directory
        mode: '0755'

    - name: Copy Helm chart to all nodes
      ansible.builtin.unarchive:
        src: "{{ playbook_dir }}/harbor/harbor-1.13.1.tgz"
        dest: /home/

    - name: Copy rancher/mirrored-pause to all nodes
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/harbor/mirrored-pause.tar"
        dest: /home/

    - name: Copy images to all nodes
      ansible.builtin.unarchive:
        src: "{{ playbook_dir }}/harbor/harbor-images.tar"
        dest: /home/

    - name: Define Harbor images list
      set_fact:
        harbor_images:
          - harbor-core
          - harbor-db
          - harbor-exporter   
          - harbor-jobservice
          - harbor-portal
          - harbor-registryctl
          - nginx-photon
          - redis-photon
          - registry-photon
          - trivy-adapter-photon

    - name: Load Harbor images using K3s ctr
      ansible.builtin.shell:
        cmd: "k3s ctr images import /home/harbor-images/{{ item }}.tar"
      loop: "{{ harbor_images }}"

- name: Execute Helm chart
  hosts: master
  gather_facts: false
  become: true
  tasks:

    - name: Install Harbor using Helm
      ansible.builtin.shell: >-
        helm install harbor --generate-name --kubeconfig /etc/rancher/k3s/k3s.yaml
      args:
        chdir: /home/

- name: Monitoring deployment
  hosts: master
  become: true
  gather_facts: false
  tasks:
    - name: Copy required .yaml files to master
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/prometheus-grafana-setup"
        dest: /home/
        mode: '0755'

    - name: Create monitoring namespace
      ansible.builtin.shell:
        cmd: kubectl create namespace monitoring

    - name: Deploy components
      ansible.builtin.shell:
        cmd: "kubectl apply -f {{ item.path }}"
      loop:
        - path: kubernetes-persistent-volume/
        - path: kubernetes-prometheus/
        - path: kube-state-metrics-configs/
        - path: kubernetes-node-exporter/
        - path: kubernetes-grafana/
