- name: Monitoring deployment
  hosts: master
  become: true
  gather_facts: false
  tasks:

    - name: Copy required .yaml files to master
      ansible.builtin.copy:
        src: /prometheus-grafana-setup
        dest: /home/
        mode: '0755'

    - name: Create monitoring namespace
      ansible.builtin.shell:
        cmd: kubectl create namespace monitoring

    - name: Persistent volumes
      ansible.builtin.shell:
        cmd: kubectl apply -f kubernetes-persistent-volume/
      args:
        chdir: /prometheus-grafana-setup/

    - name: Prometheus deployment
      ansible.builtin.shell:
        cmd: kubectl apply -f kubernetes-prometheus/
      args:
        chdir: /prometheus-grafana-setup/

    - name: kube-state-metrics deployment
      ansible.builtin.shell:
        cmd: kubectl apply -f kube-state-metrics-configs/
      args:
        chdir: /prometheus-grafana-setup/

    - name: Node-exporter deployment
      ansible.builtin.shell:
        cmd: kubectl apply -f kubernetes-node-exporter/
      args:
        chdir: /prometheus-grafana-setup/

    - name: Grafana deployment
      ansible.builtin.shell:
        cmd: kubectl apply -f kubernetes-grafana/
      args:
        chdir: /prometheus-grafana-setup/