- name: Deploy Grafana + Prometheus
  hosts: all
  become: true
  gather_facts: false
  tasks:

    - name: Define images list
      set_fact:
        images:
          - prometheus:latest
          - node-exporter:latest
          - kube-state-metrics:v2.3.0
          - grafana:latest

    - name: Load container images from Harbor
      ansible.builtin.shell:
        cmd: "ctr image pull --plain-http harbor.core.local/k3s/{{ item }}"
      loop: "{{ images }}"

- name: Copy .yaml files to master
  hosts: master
  become: true
  gather_facts: false
  tasks:

    - name: Copy .yaml files to master
      ansible.builtin.copy:
        src: /home/desktop/prometheus-grafana-setup
        dest: /home/
        mode: '0755'


    - name: Persistent volumes
      ansible.builtin.shell:
        cmd: kubectl apply -f kubernetes-persistent-volume/
      arg:
        chdir: /home/prometheus-grafana-setup/