- name: Monitoring deployment
  hosts: master
  become: true
  gather_facts: false
  tasks:
    - name: Copy required .yaml files to master
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/prometheus-grafana-setup"
        dest: /home/
        mode: '0755'

    - name: Create monitoring namespace
      ansible.builtin.shell:
        cmd: kubectl create namespace monitoring

    - name: Deploy components
      ansible.builtin.shell:
        cmd: "kubectl apply -f {{ item.path }}"
      args:
        chdir: /home/prometheus-grafana-setup/
      loop:
        - path: kubernetes-persistent-volume/
        - path: kubernetes-prometheus/
        - path: kube-state-metrics-configs/
        - path: kubernetes-node-exporter/
        - path: kubernetes-grafana/